name: Rspec

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/rspec.yml"

jobs:
  run_spec:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          make setup
          make ci.rspec